import asyncio
import edge_tts
import os
import time

# EXACT COMPLEX SSML AS GENERATED BY NEW CODE (Minimal Header, Nested Prosody)
TEXT = """
<speak>
    Todo se resume a un solo número. 
    <break time="0.8s"/> 
    <prosody rate="+10%">
      ¡el futuro es hoy!
    </prosody>
</speak>
"""
OUTPUT_FILE = "debug_audio_ramona.mp3"
VOICE = "es-DO-RamonaNeural"

async def generate_test_audio():
    print(f"🎙️ Generando audio SSML complejo...")

    
    start_time = time.time()
    communicate = edge_tts.Communicate(TEXT, VOICE)
    await communicate.save(OUTPUT_FILE)
    elapsed = time.time() - start_time
    
    print(f"✅ Generación completada en {elapsed:.2f}s")
    
    # Convert to WAV for checking
    if os.path.exists(OUTPUT_FILE):
        wav_file = OUTPUT_FILE.replace(".mp3", ".wav")
        import subprocess
        subprocess.run(f"ffmpeg -y -i {OUTPUT_FILE} {wav_file}", shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        
        if os.path.exists(wav_file):
            try:
                from moviepy import AudioFileClip
                clip = AudioFileClip(wav_file)
                print(f"🎥 Duración REAL WAV (MoviePy): {clip.duration:.2f}s")
                clip.close()
            except ImportError:
                print("⚠️ MoviePy error")
    else:
        print("❌ El archivo no se creó.")

if __name__ == "__main__":
    asyncio.run(generate_test_audio())
