# Generated by Django 5.2.5 on 2026-01-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_videoproject_dynamic_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='timestamps',
            field=models.TextField(blank=True, help_text='Timestamps de cada escena para capítulos de YouTube (formato: MM:SS - Título)'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
