# Generated by Django 5.2.5 on 2026-01-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_videoproject_timestamps_alter_videoproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='script_hashtags',
            field=models.TextField(blank=True, help_text='Hashtags extraídos del guion (# HASHTAGS: ...)'),
        ),
    ]
