# Generated by Django 5.2.5 on 2026-01-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_videoproject_script_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID after upload (prevents duplicates)', max_length=100, null=True),
        ),
    ]
