# Generated by Django 5.2.5 on 2026-01-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_videoproject_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='auto_upload_youtube',
            field=models.BooleanField(default=False, help_text='Subir automáticamente a YouTube al finalizar la generación'),
        ),
    ]
