# Generated by Django 5.2.5 on 2026-01-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_videoproject_auto_upload_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sfx/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
