# Generated by Django 5.2.5 on 2026-01-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_sfx'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='render_mode',
            field=models.CharField(choices=[('cpu', 'Procesador (CPU)'), ('gpu', 'Tarjeta NVIDIA (GPU)')], default='cpu', help_text='Método de renderizado de video', max_length=10),
        ),
    ]
