# Generated by Django 5.2.5 on 2026-02-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_videoproject_render_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='music_volume_lock',
            field=models.BooleanField(default=False, help_text='Bloquea el volumen global, los bloques no lo modifican a menos que tengan música propia'),
        ),
    ]
