# Generated by Django 5.2.5 on 2026-02-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_videoproject_music_volume_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='render_workers',
            field=models.IntegerField(default=0, help_text='Número de trabajadores paralelos (0=Lineal, 2=Recomendado para 12GB RAM)'),
        ),
    ]
