# Generated by Django 5.2.5 on 2026-02-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_videoproject_render_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='progress_total',
            field=models.FloatField(default=0.0, help_text='Progreso actual de generación (0-100)'),
        ),
    ]
