# Generated by Django 5.2.5 on 2026-02-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_videoproject_progress_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Duración total del video en segundos'),
        ),
    ]
