# Generated by Django 5.2.5 on 2026-02-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_videoproject_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproject',
            name='render_workers',
        ),
    ]
