# Generated by Django 5.2.5 on 2026-02-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_remove_videoproject_render_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='render_workers',
            field=models.IntegerField(default=4, help_text='Número de núcleos (workers) para renderizado paralelo (0=Auto, 1=Lineal)'),
        ),
    ]
