# Generated by Django 5.2.5 on 2026-02-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_videoproject_render_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproject',
            name='render_workers',
        ),
    ]
