# Generated by Django 5.2.5 on 2026-02-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_videoproject_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='dynamic_subtitles',
            field=models.BooleanField(default=False, help_text='Fuerza el modo karaoke (dinámico) para todo el video'),
        ),
    ]
