# Generated by Django 5.2.5 on 2026-03-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_videoproject_dynamic_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='youtube_privacy',
            field=models.CharField(choices=[('public', 'Público'), ('unlisted', 'Oculto'), ('private', 'Privado')], default='unlisted', max_length=20),
        ),
    ]
