# Generated by Django 5.2.5 on 2026-03-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_videoproject_youtube_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproject',
            name='youtube_privacy',
        ),
    ]
