# Generated by Django 5.2.5 on 2026-03-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0020_remove_videoproject_youtube_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='social_description',
            field=models.TextField(blank=True, help_text='Descripción editada para YouTube', null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='social_tags',
            field=models.TextField(blank=True, help_text='Tags editados para YouTube', null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='social_title',
            field=models.CharField(blank=True, help_text='Título editado para YouTube', max_length=255, null=True),
        ),
    ]
