# Generated by Django 5.2.5 on 2026-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_videoproject_social_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='social_pinned_comment',
            field=models.TextField(blank=True, help_text='Comentario fijado editado para YouTube', null=True),
        ),
    ]
