# Generated by Django 5.2.5 on 2026-03-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_videoproject_social_pinned_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='audio_attack_time',
            field=models.FloatField(blank=True, help_text='Tiempo de ataque en segundos', null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='audio_block_fade',
            field=models.FloatField(blank=True, help_text='Fade entre bloques de audio', null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='audio_ducking_ratio',
            field=models.FloatField(blank=True, help_text='Ratio de ducking (0.1 a 0.5 típico)', null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='audio_early_finish',
            field=models.FloatField(blank=True, help_text='Silencio técnico al final del bloque', null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='audio_merge_threshold',
            field=models.FloatField(blank=True, help_text='Umbral de unión de bloques de silencio', null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='audio_release_time',
            field=models.FloatField(blank=True, help_text='Tiempo de recuperación en segundos', null=True),
        ),
    ]
