# Generated by Django 5.2.5 on 2026-03-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_videoproject_audio_attack_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='subtitles_y_position',
            field=models.FloatField(default=0.7, help_text='Posición vertical global de los subtítulos (0.0=Arriba, 1.0=Abajo)'),
        ),
    ]
