# Generated by Django 5.2.5 on 2026-03-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_videoproject_subtitles_y_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='dubbing_mode',
            field=models.CharField(default='hq', help_text='Modo de doblaje (lipsync/hq)', max_length=20),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='language',
            field=models.CharField(default='es', help_text='Idioma base del guion (es/en)', max_length=10),
        ),
    ]
