# Generated by Django 5.2.5 on 2026-03-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0025_videoproject_dubbing_mode_videoproject_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproject',
            name='dubbing_mode',
            field=models.CharField(blank=True, default='', help_text='Modo de doblaje (lipsync/hq)', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='language',
            field=models.CharField(blank=True, default='', help_text='Idioma base del guion (es/en)', max_length=10),
        ),
    ]
