# Generated by Django 5.2.5 on 2026-03-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='translate_auto',
            field=models.BooleanField(default=False, help_text='Traducir automáticamente al español si la fuente es extranjera'),
        ),
    ]
